name: Deploy Bot to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./bot-source/CustomerServiceBot
    
    - name: Build with dotnet
      run: dotnet build --configuration Release CustomerServiceBot.csproj
      working-directory: ./bot-source/CustomerServiceBot

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{github.workspace}}/publish
        cp ${{github.workspace}}/publish/*.runtimeconfig.json ${{github.workspace}}/publish/
      working-directory: ./bot-source/CustomerServiceBot

    - name: Update appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{github.workspace}}/publish/appsettings.json'
      env:
        MicrosoftAppType: ${{ secrets.MICROSOFT_APP_TYPE }}
        MicrosoftAppId: ${{ secrets.MICROSOFT_APP_ID }}
        MicrosoftAppPassword: ${{ secrets.MICROSOFT_APP_PASSWORD }}
        MicrosoftAppTenantId: ${{ secrets.MICROSOFT_APP_TENANT_ID }}

    - name: Add web.config
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <location path="." inheritInChildApplications="false">
            <system.webServer>
              <handlers>
                <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
              </handlers>
              <aspNetCore processPath="dotnet" arguments=".\CustomerServiceBot.dll" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess" />
            </system.webServer>
          </location>
        </configuration>' > ${{github.workspace}}/publish/web.config

    - name: List publish directory contents
      run: ls -R ${{github.workspace}}/publish

    - name: Generate deployment package
      run: zip -r deploy.zip .
      working-directory: ${{github.workspace}}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/publish/deploy.zip

    - name: List deployed files
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        script: |
          ls -R /home/site/wwwroot