name: Deploy Bot to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
   
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
   
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./bot-source/CustomerServiceBot

    - name: Build with dotnet
      run: dotnet build --configuration Release CustomerServiceBot.csproj
      working-directory: ./bot-source/CustomerServiceBot
   
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{github.workspace}}/myapp
      working-directory: ./bot-source/CustomerServiceBot
   
    - name: Update appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{github.workspace}}/myapp/appsettings.json'
      env:
        MicrosoftAppType: ${{ secrets.MICROSOFT_APP_TYPE }}
        MicrosoftAppId: ${{ secrets.MICROSOFT_APP_ID }}
        MicrosoftAppPassword: ${{ secrets.MICROSOFT_APP_PASSWORD }}
        MicrosoftAppTenantId: ${{ secrets.MICROSOFT_APP_TENANT_ID }}

    - name: List publish directory contents
      run: ls -R ${{github.workspace}}/myapp

    - name: Generate deployment package
      run: zip -r deploy.zip . -x "*.git*"
      working-directory: ${{github.workspace}}/myapp
   
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/myapp/deploy.zip

    - name: Output Publish Profile Info
      run: |
        echo "Publish Profile Content Length: ${#PUBLISH_PROFILE}"
        echo "First 100 characters of Publish Profile:"
        echo "${PUBLISH_PROFILE:0:100}"
      env:
        PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}